---
title: Codelegy
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/blog/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
highlighter: pygments
tagline: Love Code Live Code
author:
  name: mikebutts
  email: mike@codelegy.com
  github: mikebutts
  twitter: mikelols
  feedburner: feedname
production_url: http://www.codelegy.com/blog
gems:
- jekyll-sitemap
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: codelegy
  analytics:
    provider: google
    gauges:
      site_id: SITE ID
    google:
      tracking_id: UA-94071239-1
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: 1
  sharing:
    provider: false
